### ISSUE TITLE
Doesn't works for me :/

### ISSUE THREAD

**Issue by ronv** [johnmartin/remote#1]
Errors prevented startup:

While building the application:
node_modules/jsdom/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token ILLEGAL
node_modules/jsdom/node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
node_modules/jsdom/node_modules/request/node_modules/node-uuid/test/test.html:1: bad formatting in HTML template
node_modules/jsdom/node_modules/htmlparser2/test/Documents/Attributes.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsdom/node_modules/htmlparser2/test/Documents/Basic.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

**Comment by johnmartin** [comment]
@ronv Ah yes! I forgot a step in the setup process. You need to do a `cd .meteor && npm i .` (I'll add it to the README.md)
