### ISSUE TITLE
Getting an Exited with code: 8 when building app

### ISSUE THREAD

**Issue by ErikCohenDev** [johnmartin/remote#3]
No changes were made after cloning.

Error:

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160603-19:12:03.596(-4)? (STDERR)
W20160603-19:12:03.598(-4)? (STDERR) C:\Dev\JS\remote.meteor\node_modules\jsdom\lib\jsdom.js:3
W20160603-19:12:03.598(-4)? (STDERR) () => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
W20160603-19:12:03.598(-4)? (STDERR)  ^
W20160603-19:12:03.598(-4)? (STDERR) SyntaxError: Unexpected token )
W20160603-19:12:03.599(-4)? (STDERR)     at Module._compile (module.js:439:25)
W20160603-19:12:03.599(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160603-19:12:03.599(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160603-19:12:03.599(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160603-19:12:03.599(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160603-19:12:03.599(-4)? (STDERR)     at require (module.js:380:17)
W20160603-19:12:03.600(-4)? (STDERR)     at Object.Npm.require (C:\Dev\JS\remote.meteor\local\build\programs\server\boot.js:163:18)
W20160603-19:12:03.600(-4)? (STDERR)     at app\server\update.js:1:-10
W20160603-19:12:03.600(-4)? (STDERR)     at app\server\update.js:79:4
W20160603-19:12:03.601(-4)? (STDERR)     at C:\Dev\JS\remote.meteor\local\build\programs\server\boot.js:283:10
W20160603-19:12:11.113(-4)? (STDERR)

Windows 7 64x
npm @ v3.8.1
node @ v4.4.0
Meteor @1.3.2.4 Windows Version.

**Comment by johnmartin** [comment]
@cohenpts So, I haven't run this codebase in a while and it's seems that `jsdom` has moved on. I'll have to investigate what's really going on here properly (as it's happening for me as well)
